#!/usr/bin/env bash
# DSS local launcher for macOS / Linux — the bash counterpart of start.ps1.
#
#   ./start-mac.sh           start MediaMTX + backend + frontend (background)
#   ./start-mac.sh stop      stop everything this script started
#   ./start-mac.sh restart   stop then start
#   ./start-mac.sh logs      tail all three logs
#   ./start-mac.sh status    show what's up
#
# First run creates backend/.venv (installs requirements.txt) and a SQLite
# backend/.env with random secrets. Re-runs reuse both. Open http://localhost:8080
# and sign in admin / admin (you'll be asked to change the password).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND="$ROOT/backend"
WEBDIR="$ROOT/web"
VENV="$BACKEND/.venv"
PY="$VENV/bin/python"
ENVFILE="$BACKEND/.env"
RUN="$ROOT/.run"                       # pids + logs (gitignored)
MTX="$ROOT/mediamtx"                   # macOS/Linux binary (not mediamtx.exe)
MTXCFG="$ROOT/mediamtx.yml"
G2DIR="$ROOT/.go2rtc"                   # go2rtc runtime (binary + live config)
G2BIN="$G2DIR/go2rtc"
G2VER="v1.9.14"

mkdir -p "$RUN"
c_ok()   { printf "\033[32m✓ %s\033[0m\n" "$*"; }
c_step() { printf "\033[36m→ %s\033[0m\n" "$*"; }
c_warn() { printf "\033[33m! %s\033[0m\n" "$*"; }
c_err()  { printf "\033[31m✗ %s\033[0m\n" "$*" >&2; }

port_up()  { nc -z -G 1 127.0.0.1 "$1" >/dev/null 2>&1; }
wait_port() {  # wait_port <port> <name> <tries>
  local p=$1 name=$2 n=${3:-20}
  for ((i=0; i<n; i++)); do port_up "$p" && { c_ok "$name on :$p"; return 0; }; sleep 0.5; done
  c_err "$name did not come up on :$p (see $RUN/$name.log)"; return 1
}

start_one() {  # start_one <name> <port> <workdir> <cmd...>
  local name=$1 port=$2 wd=$3; shift 3
  if port_up "$port"; then c_warn "$name port :$port already in use — skipping"; return 0; fi
  c_step "Starting $name"
  ( cd "$wd" && exec "$@" ) >"$RUN/$name.log" 2>&1 &
  echo $! > "$RUN/$name.pid"
  disown 2>/dev/null || true            # survive the launching shell exiting
}

stop_all() {
  local any=0
  for name in frontend backend mediamtx go2rtc; do
    local pf="$RUN/$name.pid"
    [ -f "$pf" ] || continue
    local pid; pid="$(cat "$pf")"
    if kill -0 "$pid" 2>/dev/null; then c_step "Stopping $name (pid $pid)"; kill "$pid" 2>/dev/null || true; any=1; fi
    rm -f "$pf"
  done
  [ "$any" = 1 ] && c_ok "stopped" || c_warn "nothing was running (per pidfiles)"
}

case "${1:-start}" in
  stop)    stop_all; exit 0 ;;
  restart) stop_all; sleep 1 ;;
  logs)    exec tail -n 40 -f "$RUN"/mediamtx.log "$RUN"/backend.log "$RUN"/frontend.log ;;
  status)
    for p in 9997:MediaMTX 8000:Backend 8080:Frontend 8889:WHEP 8888:HLS; do
      port_up "${p%%:*}" && c_ok "${p##*:} (${p%%:*})" || c_warn "${p##*:} (${p%%:*}) down"
    done; exit 0 ;;
  start) ;;
  *) c_err "usage: $0 [start|stop|restart|logs|status]"; exit 2 ;;
esac

# ── prerequisites ────────────────────────────────────────────────────────────
command -v python3 >/dev/null || { c_err "python3 not found"; exit 1; }
[ -x "$MTX" ] || { c_err "mediamtx binary not found/executable at $MTX"; exit 1; }
[ -f "$MTXCFG" ] || { c_err "mediamtx.yml not found at $MTXCFG"; exit 1; }

# ── venv + deps (first run) ──────────────────────────────────────────────────
if [ ! -x "$PY" ]; then
  c_step "Creating venv + installing backend deps (first run, ~1 min)"
  python3 -m venv "$VENV"
  "$PY" -m pip install -q --upgrade pip
  # requirements.txt pins fastapi>=0.115; a fresh install pulls a current build
  # that handles `from __future__ import annotations` + 204 routes (0.115.2 does not).
  "$PY" -m pip install -q -r "$BACKEND/requirements.txt"
  c_ok "deps installed"
else
  c_ok "venv present"
fi

# ── .env (first run) ─────────────────────────────────────────────────────────
if [ ! -f "$ENVFILE" ]; then
  c_step "Generating backend/.env with random secrets (SQLite, local dev)"
  JWT="$("$PY" -c 'import secrets; print(secrets.token_hex(48))')"
  FERNET="$("$PY" -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"
  cat > "$ENVFILE" <<EOF
# Generated by start-mac.sh — local dev only, do not commit.
DATABASE_URL=sqlite+aiosqlite:///./dss.db
JWT_SECRET=$JWT
NVR_SECRET_KEY=$FERNET
CORS_ORIGINS=["http://localhost:8080"]
MEDIAMTX_API_URL=http://localhost:9997
MEDIAMTX_WEBRTC_URL=http://localhost:8889
MEDIAMTX_HLS_URL=http://localhost:8888
MEDIAMTX_RTSP_URL=rtsp://localhost:8554
MEDIAMTX_MANAGED=false
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=admin
# DEBUG=true lets the admin/admin bootstrap pass the insecure-default guard.
# Remove it (and set real secrets) for anything other than local dev.
DEBUG=true
EOF
  c_ok "backend/.env created"
else
  c_ok "backend/.env present"
fi

# SQLite needs no migrations (schema is created on first boot). Postgres users
# should run `alembic upgrade head` themselves.
grep -q 'postgresql' "$ENVFILE" && c_warn "Postgres DATABASE_URL detected — ensure it's up and migrated" \
                                 || c_ok "SQLite backend (no Postgres needed)"

# ── relay: go2rtc (buffered MSE) or mediamtx (legacy WebRTC) ──────────────────
RELAY="$(sed -n 's/^RELAY=//p' "$ENVFILE" 2>/dev/null | tr -d '[:space:]')"
RELAY="${RELAY:-mediamtx}"

ensure_go2rtc() {
  mkdir -p "$G2DIR"
  if [ ! -x "$G2BIN" ]; then
    c_step "Downloading go2rtc $G2VER (first run)"
    local arch; arch="$(uname -m)"; [ "$arch" = "x86_64" ] && arch="amd64" || arch="arm64"
    local os; os="$(uname -s | tr 'A-Z' 'a-z')"   # darwin / linux
    curl -sL -m 120 -o "$G2DIR/go2rtc.zip" \
      "https://github.com/AlexxIT/go2rtc/releases/download/$G2VER/go2rtc_${os}_${arch}.zip" \
      && unzip -o -q "$G2DIR/go2rtc.zip" -d "$G2DIR" && chmod +x "$G2BIN" && rm -f "$G2DIR/go2rtc.zip" \
      || { c_err "go2rtc download failed"; return 1; }
    c_ok "go2rtc installed"
  fi
  # Fresh runtime config from the committed template (no secrets — the backend
  # registers streams via the go2rtc API on startup).
  cp "$ROOT/go2rtc.base.yaml" "$G2DIR/go2rtc.yaml"
}

# ── launch ───────────────────────────────────────────────────────────────────
if [ "$RELAY" = "go2rtc" ]; then
  ensure_go2rtc || exit 1
  start_one go2rtc 1984 "$G2DIR" "$G2BIN" -config "$G2DIR/go2rtc.yaml"
  wait_port 1984 go2rtc 15
else
  start_one mediamtx 9997 "$ROOT" "$MTX" "$MTXCFG"
  wait_port 9997 mediamtx 15
fi

start_one backend  8000 "$BACKEND" "$PY" -m uvicorn app.main:app --host 0.0.0.0 --port 8000
wait_port 8000 backend 25

# Prefer the new React build (web-react/dist) when it's been built; fall back to
# the legacy vanilla UI in web/. Build it with: (cd web-react && npm run build)
SERVEDIR="$WEBDIR"
if [ -f "$ROOT/web-react/dist/index.html" ]; then
  SERVEDIR="$ROOT/web-react/dist"
  c_ok "Serving React UI (web-react/dist)"
else
  c_warn "React build not found — serving legacy web/ (run: cd web-react && npm run build)"
fi
start_one frontend 8080 "$SERVEDIR"  "$PY" -m http.server 8080
wait_port 8080 frontend 10

echo
c_ok "DSS is up:"
echo "  Frontend  http://localhost:8080"
echo "  API docs  http://localhost:8000/docs"
if [ "$RELAY" = "go2rtc" ]; then
  echo "  go2rtc    http://localhost:1984  (relay=go2rtc, buffered MSE)"
else
  echo "  MediaMTX  http://localhost:9997/v3/paths/list"
fi
echo
echo "Login: admin / admin (you'll be asked to change it)."
echo "Stop with:  ./start-mac.sh stop      Logs:  ./start-mac.sh logs"

[ "${DSS_NO_BROWSER:-}" = "1" ] || open "http://localhost:8080" 2>/dev/null || true
