<#
.SYNOPSIS
  One-shot launcher for local dev (no Docker).

.DESCRIPTION
  First run:
    - creates backend/.venv and installs deps
    - generates backend/.env with random JWT_SECRET + NVR_SECRET_KEY
    - runs alembic upgrade head
    - seeds from nvr_inventory.json (assigns NVRs to region 'central')
  Every run:
    - launches three child windows: MediaMTX, FastAPI backend, static frontend
    - opens the browser at http://localhost:8080

.PARAMETER SkipBrowser
  Don't auto-open the browser at the end.

.PARAMETER ReSeed
  Re-run the seed step even if backend/.env already exists.

.EXAMPLE
  .\start.ps1
  .\start.ps1 -SkipBrowser
  .\start.ps1 -ReSeed
#>
[CmdletBinding()]
param(
    [switch]$SkipBrowser,
    [switch]$ReSeed
)

$ErrorActionPreference = "Stop"
$root     = $PSScriptRoot
$backend  = Join-Path $root "backend"
$venv     = Join-Path $backend ".venv"
$envFile  = Join-Path $backend ".env"
$pyVenv   = Join-Path $venv "Scripts\python.exe"
$mtxExe   = Join-Path $root "mediamtx.exe"
$mtxCfg   = Join-Path $root "mediamtx.yml"
$webDir   = Join-Path $root "web"

# Helpers -----------------------------------------------------------------

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "    $msg"  -ForegroundColor Green }
function Write-Warn2($msg){ Write-Host "    $msg"  -ForegroundColor Yellow }

function Require-Cmd($name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "Required tool '$name' not found on PATH."
    }
}

function Wait-ForPort($port, $name, $timeoutSec = 30) {
    $deadline = (Get-Date).AddSeconds($timeoutSec)
    while ((Get-Date) -lt $deadline) {
        $sock = New-Object System.Net.Sockets.TcpClient
        try {
            $iar = $sock.BeginConnect("127.0.0.1", $port, $null, $null)
            if ($iar.AsyncWaitHandle.WaitOne(500) -and $sock.Connected) {
                $sock.EndConnect($iar) | Out-Null
                $sock.Close()
                Write-Ok "$name is up on :$port"
                return $true
            }
        } catch {}
        finally { $sock.Close() }
        Start-Sleep -Milliseconds 500
    }
    Write-Warn2 "$name did not open :$port within ${timeoutSec}s (continuing anyway)"
    return $false
}

# Sanity ------------------------------------------------------------------

Write-Step "Sanity checks"
Require-Cmd "py"
if (-not (Test-Path $mtxExe)) { throw "mediamtx.exe not found at $mtxExe" }
if (-not (Test-Path $mtxCfg)) { throw "mediamtx.yml not found at $mtxCfg" }
if (-not (Test-Path $backend)) { throw "backend/ not found at $backend" }
Write-Ok "py, mediamtx.exe, backend/ all present"

# venv + deps -------------------------------------------------------------

if (-not (Test-Path $pyVenv)) {
    Write-Step "Creating virtualenv at backend/.venv"
    py -m venv $venv
    Write-Ok "venv created"

    Write-Step "Installing backend dependencies (one-time)"
    & $pyVenv -m pip install --upgrade pip
    & $pyVenv -m pip install -r (Join-Path $backend "requirements.txt")
    Write-Ok "deps installed"
} else {
    Write-Ok "venv already present"
}

# .env (first-run only) ---------------------------------------------------

$freshEnv = $false
if (-not (Test-Path $envFile)) {
    Write-Step "Generating backend/.env with random secrets"
    $jwt = & $pyVenv -c "import secrets; print(secrets.token_hex(48))"
    $fernet = & $pyVenv -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    @"
# Generated by start.ps1 on $(Get-Date -Format o). Do not commit.
DATABASE_URL=postgresql+asyncpg://dss:dss@localhost:5432/dss
JWT_SECRET=$jwt
NVR_SECRET_KEY=$fernet
CORS_ORIGINS=["http://localhost:8080"]
MEDIAMTX_API_URL=http://localhost:9997
MEDIAMTX_WEBRTC_URL=http://localhost:8889
MEDIAMTX_HLS_URL=http://localhost:8888
MEDIAMTX_RTSP_URL=rtsp://localhost:8554
MEDIAMTX_MANAGED=false
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=admin
"@ | Out-File -FilePath $envFile -Encoding ascii
    Write-Ok "backend/.env created"
    $freshEnv = $true
} else {
    Write-Ok "backend/.env already present"
}

# Postgres reachability ---------------------------------------------------

Write-Step "Checking Postgres on :5432"
$pgUp = $false
try {
    $sock = New-Object System.Net.Sockets.TcpClient
    $iar = $sock.BeginConnect("127.0.0.1", 5432, $null, $null)
    if ($iar.AsyncWaitHandle.WaitOne(1000) -and $sock.Connected) {
        $pgUp = $true
        $sock.EndConnect($iar) | Out-Null
    }
    $sock.Close()
} catch {}
if (-not $pgUp) {
    Write-Warn2 "Cannot reach :5432. Backend will fail to start without it."
    Write-Warn2 "Install (once, in an Administrator PowerShell):"
    Write-Warn2 "  winget install --silent --accept-package-agreements --accept-source-agreements PostgreSQL.PostgreSQL"
    Write-Warn2 "Then create the DB and user (replace 17 with your installed version):"
    Write-Warn2 '  $env:PGPASSWORD = "postgres"'
    Write-Warn2 '  & "C:\Program Files\PostgreSQL\17\bin\psql.exe" -U postgres -h localhost -c "CREATE USER dss WITH PASSWORD ''dss'';"'
    Write-Warn2 '  & "C:\Program Files\PostgreSQL\17\bin\psql.exe" -U postgres -h localhost -c "CREATE DATABASE dss OWNER dss;"'
    throw "PostgreSQL is not reachable on localhost:5432 -- aborting."
} else {
    Write-Ok "Postgres reachable"
}

# Migrations + seed -------------------------------------------------------

if ($freshEnv -or $ReSeed) {
    Write-Step "Running alembic upgrade head"
    Push-Location $backend
    try {
        & $pyVenv -m alembic upgrade head
        Write-Ok "schema up to date"

        $inventory = Join-Path $root "nvr_inventory.json"
        if (Test-Path $inventory) {
            Write-Step "Seeding inventory from nvr_inventory.json"
            & $pyVenv -m app.seed --inventory $inventory --region-slug central
            Write-Ok "seed complete"
        } else {
            Write-Warn2 "nvr_inventory.json not found - skipping seed. Add NVRs later via /api/v1/nvrs."
        }
    } finally {
        Pop-Location
    }
} else {
    Write-Ok "Existing .env detected - skipping migrate/seed. Use -ReSeed to force."
}

# Launch the three processes ---------------------------------------------

Write-Step "Starting MediaMTX (window 1)"
$mtxCmd = "Set-Location '$root'; `$Host.UI.RawUI.WindowTitle='DSS MediaMTX'; & '$mtxExe' '$mtxCfg'"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $mtxCmd | Out-Null

Wait-ForPort 9997 "MediaMTX" 15 | Out-Null

Write-Step "Starting FastAPI backend (window 2)"
$backendCmd = "Set-Location '$backend'; `$Host.UI.RawUI.WindowTitle='DSS Backend'; " +
              "& '$pyVenv' -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $backendCmd | Out-Null

Wait-ForPort 8000 "Backend" 20 | Out-Null

Write-Step "Starting static frontend (window 3)"
$frontendCmd = "Set-Location '$webDir'; `$Host.UI.RawUI.WindowTitle='DSS Frontend'; " +
               "& '$pyVenv' -m http.server 8080"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $frontendCmd | Out-Null

Wait-ForPort 8080 "Frontend" 10 | Out-Null

# Done --------------------------------------------------------------------

Write-Host ""
Write-Host "DSS is up:" -ForegroundColor Green
Write-Host "  Frontend  http://localhost:8080"     -ForegroundColor Green
Write-Host "  API docs  http://localhost:8000/docs" -ForegroundColor Green
Write-Host "  MediaMTX  http://localhost:9997/v3/paths/list" -ForegroundColor Green
Write-Host ""
Write-Host "Login: admin / admin (will require password change on first sign-in)." -ForegroundColor Yellow
Write-Host "Stop everything by closing the three PowerShell windows." -ForegroundColor Yellow

if (-not $SkipBrowser) {
    Start-Process "http://localhost:8080"
}
