<#
.SYNOPSIS
  One-shot launcher for local dev (no Docker).

.DESCRIPTION
  First run:
    - creates backend/.venv and installs deps
    - generates backend/.env with random JWT_SECRET + NVR_SECRET_KEY
    - runs alembic upgrade head (Postgres) — SQLite uses create_all on first boot
  Every run:
    - launches three child windows: MediaMTX, FastAPI backend, static frontend
    - opens the browser at http://localhost:8080

  NVRs and cameras are managed manually via the admin UI; no inventory
  auto-seed runs at startup.

.PARAMETER SkipBrowser
  Don't auto-open the browser at the end.

.EXAMPLE
  .\start.ps1
  .\start.ps1 -SkipBrowser
#>
[CmdletBinding()]
param(
    [switch]$SkipBrowser
)

$ErrorActionPreference = "Stop"
$root     = $PSScriptRoot
$backend  = Join-Path $root "backend"
$venv     = Join-Path $backend ".venv"
$envFile  = Join-Path $backend ".env"
$pyVenv   = Join-Path $venv "Scripts\python.exe"
$mtxExe   = Join-Path $root "mediamtx.exe"
$mtxCfg   = Join-Path $root "mediamtx.yml"
$webDir   = Join-Path $root "web-react\dist"   # React UI build (legacy web/ removed)

# Helpers -----------------------------------------------------------------

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "    $msg"  -ForegroundColor Green }
function Write-Warn2($msg){ Write-Host "    $msg"  -ForegroundColor Yellow }

function Require-Cmd($name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "Required tool '$name' not found on PATH."
    }
}

function Wait-ForPort($port, $name, $timeoutSec = 30) {
    $deadline = (Get-Date).AddSeconds($timeoutSec)
    while ((Get-Date) -lt $deadline) {
        $sock = New-Object System.Net.Sockets.TcpClient
        try {
            $iar = $sock.BeginConnect("127.0.0.1", $port, $null, $null)
            if ($iar.AsyncWaitHandle.WaitOne(500) -and $sock.Connected) {
                $sock.EndConnect($iar) | Out-Null
                $sock.Close()
                Write-Ok "$name is up on :$port"
                return $true
            }
        } catch {}
        finally { $sock.Close() }
        Start-Sleep -Milliseconds 500
    }
    Write-Warn2 "$name did not open :$port within ${timeoutSec}s (continuing anyway)"
    return $false
}

# Sanity ------------------------------------------------------------------

Write-Step "Sanity checks"
Require-Cmd "py"
if (-not (Test-Path $mtxExe)) { throw "mediamtx.exe not found at $mtxExe" }
if (-not (Test-Path $mtxCfg)) { throw "mediamtx.yml not found at $mtxCfg" }
if (-not (Test-Path $backend)) { throw "backend/ not found at $backend" }
Write-Ok "py, mediamtx.exe, backend/ all present"

# venv + deps -------------------------------------------------------------

if (-not (Test-Path $pyVenv)) {
    Write-Step "Creating virtualenv at backend/.venv"
    py -m venv $venv
    Write-Ok "venv created"

    Write-Step "Installing backend dependencies (one-time)"
    & $pyVenv -m pip install --upgrade pip
    & $pyVenv -m pip install -r (Join-Path $backend "requirements.txt")
    Write-Ok "deps installed"
} else {
    Write-Ok "venv already present"
}

# .env (first-run only) ---------------------------------------------------

$freshEnv = $false
if (-not (Test-Path $envFile)) {
    Write-Step "Generating backend/.env with random secrets"
    $jwt = & $pyVenv -c "import secrets; print(secrets.token_hex(48))"
    $fernet = & $pyVenv -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    @"
# Generated by start.ps1 on $(Get-Date -Format o). Do not commit.
# SQLite for local dev. For prod: postgresql+asyncpg://dss:dss@host:5432/dss
DATABASE_URL=sqlite+aiosqlite:///./dss.db
JWT_SECRET=$jwt
NVR_SECRET_KEY=$fernet
CORS_ORIGINS=["http://localhost:8080"]
MEDIAMTX_API_URL=http://localhost:9997
MEDIAMTX_WEBRTC_URL=http://localhost:8889
MEDIAMTX_HLS_URL=http://localhost:8888
MEDIAMTX_RTSP_URL=rtsp://localhost:8554
MEDIAMTX_MANAGED=false
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=admin
"@ | Out-File -FilePath $envFile -Encoding ascii
    Write-Ok "backend/.env created"
    $freshEnv = $true
} else {
    Write-Ok "backend/.env already present"
}

# Database backend detection ---------------------------------------------
# DSS defaults to SQLite (file backend/dss.db) for zero-install local dev.
# If the operator has switched DATABASE_URL to Postgres, we honour that and
# probe :5432; otherwise we skip the probe entirely.

$dbUrl = (Select-String -Path $envFile -Pattern '^DATABASE_URL=' -SimpleMatch | Select-Object -First 1).Line
$usingPostgres = $dbUrl -match 'postgresql'

if ($usingPostgres) {
    Write-Step "Checking Postgres on :5432"
    $pgUp = $false
    try {
        $sock = New-Object System.Net.Sockets.TcpClient
        $iar = $sock.BeginConnect("127.0.0.1", 5432, $null, $null)
        if ($iar.AsyncWaitHandle.WaitOne(1000) -and $sock.Connected) {
            $pgUp = $true
            $sock.EndConnect($iar) | Out-Null
        }
        $sock.Close()
    } catch {}
    if (-not $pgUp) {
        Write-Warn2 "Cannot reach :5432. Backend will fail to start with this DATABASE_URL."
        throw "PostgreSQL is not reachable on localhost:5432 -- aborting."
    }
    Write-Ok "Postgres reachable"
} else {
    Write-Ok "Using SQLite backend (no Postgres required)"
}

# Migrations --------------------------------------------------------------
# SQLite: schema is created automatically by the backend on first startup
# (Base.metadata.create_all in lifespan). Alembic only runs for Postgres.
# Inventory seeding is disabled — add NVRs manually from the admin UI.

if ($freshEnv -and $usingPostgres) {
    Push-Location $backend
    try {
        Write-Step "Running alembic upgrade head"
        & $pyVenv -m alembic upgrade head
        Write-Ok "schema up to date"
    } finally {
        Pop-Location
    }
} elseif ($freshEnv) {
    Write-Ok "SQLite: schema will be created by the backend on first start"
} else {
    Write-Ok "Existing .env detected - no migrations needed"
}

# Launch the three processes ---------------------------------------------

Write-Step "Starting MediaMTX (window 1)"
$mtxCmd = "Set-Location '$root'; `$Host.UI.RawUI.WindowTitle='DSS MediaMTX'; & '$mtxExe' '$mtxCfg'"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $mtxCmd | Out-Null

Wait-ForPort 9997 "MediaMTX" 15 | Out-Null

Write-Step "Starting FastAPI backend (window 2)"
$backendCmd = "Set-Location '$backend'; `$Host.UI.RawUI.WindowTitle='DSS Backend'; " +
              "& '$pyVenv' -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $backendCmd | Out-Null

Wait-ForPort 8000 "Backend" 20 | Out-Null

Write-Step "Starting static frontend (window 3)"
$frontendCmd = "Set-Location '$webDir'; `$Host.UI.RawUI.WindowTitle='DSS Frontend'; " +
               "& '$pyVenv' -m http.server 8080"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $frontendCmd | Out-Null

Wait-ForPort 8080 "Frontend" 10 | Out-Null

# Done --------------------------------------------------------------------

Write-Host ""
Write-Host "DSS is up:" -ForegroundColor Green
Write-Host "  Frontend  http://localhost:8080"     -ForegroundColor Green
Write-Host "  API docs  http://localhost:8000/docs" -ForegroundColor Green
Write-Host "  MediaMTX  http://localhost:9997/v3/paths/list" -ForegroundColor Green
Write-Host ""
Write-Host "Login: admin / admin (will require password change on first sign-in)." -ForegroundColor Yellow
Write-Host "Stop everything by closing the three PowerShell windows." -ForegroundColor Yellow

if (-not $SkipBrowser) {
    Start-Process "http://localhost:8080"
}
