<#
.SYNOPSIS
  One-shot launcher for local dev (no Docker).

.DESCRIPTION
  First run:
    - creates backend/.venv and installs deps
    - generates backend/.env with random JWT_SECRET + NVR_SECRET_KEY
    - runs alembic upgrade head (Postgres) — SQLite uses create_all on first boot
  Every run:
    - launches three child windows: MediaMTX, FastAPI backend, static frontend
    - opens the browser at http://localhost:8080

  NVRs and cameras are managed manually via the admin UI; no inventory
  auto-seed runs at startup.

.PARAMETER SkipBrowser
  Don't auto-open the browser at the end.

.EXAMPLE
  .\start.ps1
  .\start.ps1 -SkipBrowser
#>
[CmdletBinding()]
param(
    [switch]$SkipBrowser
)

$ErrorActionPreference = "Stop"
$root     = $PSScriptRoot
$backend  = Join-Path $root "backend"
$venv     = Join-Path $backend ".venv"
$envFile  = Join-Path $backend ".env"
$pyVenv   = Join-Path $venv "Scripts\python.exe"
$mtxExe   = Join-Path $root "mediamtx.exe"
$mtxCfg   = Join-Path $root "mediamtx.yml"
$webDir   = Join-Path $root "web-react\dist"   # React UI build (legacy web/ removed)
$g2Dir    = Join-Path $root ".go2rtc"          # go2rtc runtime (binary + live config)
$g2Bin    = Join-Path $g2Dir "go2rtc.exe"
$g2Cfg    = Join-Path $g2Dir "go2rtc.yaml"
$g2Ver    = "v1.9.14"

# Helpers -----------------------------------------------------------------

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "    $msg"  -ForegroundColor Green }
function Write-Warn2($msg){ Write-Host "    $msg"  -ForegroundColor Yellow }

function Require-Cmd($name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "Required tool '$name' not found on PATH."
    }
}

function Wait-ForPort($port, $name, $timeoutSec = 30) {
    $deadline = (Get-Date).AddSeconds($timeoutSec)
    while ((Get-Date) -lt $deadline) {
        $sock = New-Object System.Net.Sockets.TcpClient
        try {
            $iar = $sock.BeginConnect("127.0.0.1", $port, $null, $null)
            if ($iar.AsyncWaitHandle.WaitOne(500) -and $sock.Connected) {
                $sock.EndConnect($iar) | Out-Null
                $sock.Close()
                Write-Ok "$name is up on :$port"
                return $true
            }
        } catch {}
        finally { $sock.Close() }
        Start-Sleep -Milliseconds 500
    }
    Write-Warn2 "$name did not open :$port within ${timeoutSec}s (continuing anyway)"
    return $false
}

# Sanity ------------------------------------------------------------------

Write-Step "Sanity checks"
Require-Cmd "py"
if (-not (Test-Path $backend)) { throw "backend/ not found at $backend" }
if (-not (Test-Path (Join-Path $webDir "index.html"))) {
    throw "React UI not built. Run:  cd web-react; npm install; npm run build"
}
Write-Ok "py, backend/, web-react/dist present"

# Download + stage go2rtc (default relay). MediaMTX (legacy relay) is checked
# at launch instead, since it's optional now.
function Ensure-Go2rtc {
    New-Item -ItemType Directory -Force -Path $g2Dir | Out-Null
    if (-not (Test-Path $g2Bin)) {
        Write-Step "Downloading go2rtc $g2Ver (first run)"
        $arch = if ([Environment]::Is64BitOperatingSystem) { "win64" } else { "win32" }
        $url  = "https://github.com/AlexxIT/go2rtc/releases/download/$g2Ver/go2rtc_$arch.zip"
        $zip  = Join-Path $g2Dir "go2rtc.zip"
        try {
            Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
            Expand-Archive -Path $zip -DestinationPath $g2Dir -Force
            Remove-Item $zip -Force
        } catch { throw "go2rtc download failed: $_" }
        Write-Ok "go2rtc installed"
    }
    # Fresh runtime config from the committed template (no secrets — the backend
    # registers streams via the go2rtc API on startup).
    Copy-Item (Join-Path $root "go2rtc.base.yaml") $g2Cfg -Force
}

# venv + deps -------------------------------------------------------------

if (-not (Test-Path $pyVenv)) {
    Write-Step "Creating virtualenv at backend/.venv"
    py -m venv $venv
    Write-Ok "venv created"

    Write-Step "Installing backend dependencies (one-time)"
    & $pyVenv -m pip install --upgrade pip
    & $pyVenv -m pip install -r (Join-Path $backend "requirements.txt")
    Write-Ok "deps installed"
} else {
    Write-Ok "venv already present"
}

# .env (first-run only) ---------------------------------------------------

$freshEnv = $false
if (-not (Test-Path $envFile)) {
    Write-Step "Generating backend/.env with random secrets"
    $jwt = & $pyVenv -c "import secrets; print(secrets.token_hex(48))"
    $fernet = & $pyVenv -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    @"
# Generated by start.ps1 on $(Get-Date -Format o). Do not commit.
# SQLite for local dev. For prod: postgresql+asyncpg://dss:dss@host:5432/dss
DATABASE_URL=sqlite+aiosqlite:///./dss.db
JWT_SECRET=$jwt
NVR_SECRET_KEY=$fernet
CORS_ORIGINS=["http://localhost:8080"]
RELAY=go2rtc
MEDIAMTX_API_URL=http://localhost:9997
MEDIAMTX_WEBRTC_URL=http://localhost:8889
MEDIAMTX_HLS_URL=http://localhost:8888
MEDIAMTX_RTSP_URL=rtsp://localhost:8554
MEDIAMTX_MANAGED=false
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=admin
"@ | Out-File -FilePath $envFile -Encoding ascii
    Write-Ok "backend/.env created"
    $freshEnv = $true
} else {
    Write-Ok "backend/.env already present"
}

# Database backend detection ---------------------------------------------
# DSS defaults to SQLite (file backend/dss.db) for zero-install local dev.
# If the operator has switched DATABASE_URL to Postgres, we honour that and
# probe :5432; otherwise we skip the probe entirely.

$dbUrl = (Select-String -Path $envFile -Pattern '^DATABASE_URL=' -SimpleMatch | Select-Object -First 1).Line
$usingPostgres = $dbUrl -match 'postgresql'

if ($usingPostgres) {
    Write-Step "Checking Postgres on :5432"
    $pgUp = $false
    try {
        $sock = New-Object System.Net.Sockets.TcpClient
        $iar = $sock.BeginConnect("127.0.0.1", 5432, $null, $null)
        if ($iar.AsyncWaitHandle.WaitOne(1000) -and $sock.Connected) {
            $pgUp = $true
            $sock.EndConnect($iar) | Out-Null
        }
        $sock.Close()
    } catch {}
    if (-not $pgUp) {
        Write-Warn2 "Cannot reach :5432. Backend will fail to start with this DATABASE_URL."
        throw "PostgreSQL is not reachable on localhost:5432 -- aborting."
    }
    Write-Ok "Postgres reachable"
} else {
    Write-Ok "Using SQLite backend (no Postgres required)"
}

# Migrations --------------------------------------------------------------
# SQLite: schema is created automatically by the backend on first startup
# (Base.metadata.create_all in lifespan). Alembic only runs for Postgres.
# Inventory seeding is disabled — add NVRs manually from the admin UI.

if ($freshEnv -and $usingPostgres) {
    Push-Location $backend
    try {
        Write-Step "Running alembic upgrade head"
        & $pyVenv -m alembic upgrade head
        Write-Ok "schema up to date"
    } finally {
        Pop-Location
    }
} elseif ($freshEnv) {
    Write-Ok "SQLite: schema will be created by the backend on first start"
} else {
    Write-Ok "Existing .env detected - no migrations needed"
}

# Launch the three processes ---------------------------------------------

# Relay: go2rtc (buffered MSE — what the React UI speaks) or mediamtx (legacy).
$relayLine = (Select-String -Path $envFile -Pattern '^RELAY=' -SimpleMatch | Select-Object -First 1).Line
$relay = if ($relayLine) { ($relayLine -replace '^RELAY=', '').Trim() } else { 'go2rtc' }

if ($relay -eq 'go2rtc') {
    Ensure-Go2rtc
    Write-Step "Starting go2rtc (window 1)"
    $g2Cmd = "Set-Location '$g2Dir'; `$Host.UI.RawUI.WindowTitle='DSS go2rtc'; & '$g2Bin' -config '$g2Cfg'"
    Start-Process powershell -ArgumentList "-NoExit", "-Command", $g2Cmd | Out-Null
    Wait-ForPort 1984 "go2rtc" 15 | Out-Null
} else {
    if (-not (Test-Path $mtxExe)) { throw "mediamtx.exe not found at $mtxExe (RELAY=mediamtx)" }
    if (-not (Test-Path $mtxCfg)) { throw "mediamtx.yml not found at $mtxCfg" }
    Write-Step "Starting MediaMTX (window 1)"
    $mtxCmd = "Set-Location '$root'; `$Host.UI.RawUI.WindowTitle='DSS MediaMTX'; & '$mtxExe' '$mtxCfg'"
    Start-Process powershell -ArgumentList "-NoExit", "-Command", $mtxCmd | Out-Null
    Wait-ForPort 9997 "MediaMTX" 15 | Out-Null
}

Write-Step "Starting FastAPI backend (window 2)"
$backendCmd = "Set-Location '$backend'; `$Host.UI.RawUI.WindowTitle='DSS Backend'; " +
              "& '$pyVenv' -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $backendCmd | Out-Null

Wait-ForPort 8000 "Backend" 20 | Out-Null

# go2rtc stream registry fix (Windows) -----------------------------------
# The backend (cwd=backend/) writes the camera streams into go2rtc's config on
# its startup reconcile (GO2RTC_CONFIG_PATH in backend/.env pins the absolute
# path so it lands in THIS file, not backend/.go2rtc/). But go2rtc's POST
# /api/restart only reloads the config *display* — it does NOT re-init the
# stream registry, so streams stay unservable ("stream not found"). A hard
# process restart makes go2rtc actually load and serve them.
if ($relay -eq 'go2rtc') {
    Start-Sleep -Seconds 2   # let the startup reconcile finish writing the YAML
    Write-Step "Reloading go2rtc to pick up backend-written streams"
    Get-Process go2rtc -ErrorAction SilentlyContinue | Stop-Process -Force
    Start-Sleep -Milliseconds 800
    $g2Cmd2 = "Set-Location '$g2Dir'; `$Host.UI.RawUI.WindowTitle='DSS go2rtc'; & '$g2Bin' -config '$g2Cfg'"
    Start-Process powershell -ArgumentList "-NoExit", "-Command", $g2Cmd2 | Out-Null
    Wait-ForPort 1984 "go2rtc" 15 | Out-Null
}

Write-Step "Starting static frontend (window 3)"
$frontendCmd = "Set-Location '$webDir'; `$Host.UI.RawUI.WindowTitle='DSS Frontend'; " +
               "& '$pyVenv' -m http.server 8080"
Start-Process powershell -ArgumentList "-NoExit", "-Command", $frontendCmd | Out-Null

Wait-ForPort 8080 "Frontend" 10 | Out-Null

# Done --------------------------------------------------------------------

Write-Host ""
Write-Host "DSS is up:" -ForegroundColor Green
Write-Host "  Frontend  http://localhost:8080"     -ForegroundColor Green
Write-Host "  API docs  http://localhost:8000/docs" -ForegroundColor Green
if ($relay -eq 'go2rtc') {
    Write-Host "  go2rtc    http://localhost:1984  (relay=go2rtc, buffered MSE)" -ForegroundColor Green
} else {
    Write-Host "  MediaMTX  http://localhost:9997/v3/paths/list" -ForegroundColor Green
}
Write-Host ""
Write-Host "Login: admin / admin (will require password change on first sign-in)." -ForegroundColor Yellow
Write-Host "Stop everything by closing the three PowerShell windows." -ForegroundColor Yellow

if (-not $SkipBrowser) {
    Start-Process "http://localhost:8080"
}
