#!/usr/bin/env bash
#
# Build the OFFLINE Docker bundle for Kanagatly VMS.
#
# Run this ONCE on an internet-connected machine that has Docker. It builds the
# images (backend + Caddy, with the SPA + ffmpeg baked in), pulls the external
# images (go2rtc, postgres), and packs everything into a single folder you copy
# to the air-gapped server. Nothing on the target server needs the internet.
#
#   ./deploy/docker/build-offline-bundle.sh [output-dir]
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
OUT="${1:-$ROOT/kanagatly-vms-offline}"

GO2RTC_IMG="alexxit/go2rtc:1.9.14"
PG_IMG="postgres:16-alpine"

cd "$ROOT"

echo "==> Building app images (backend + Caddy)…"
# Dummy secrets just satisfy compose interpolation during build; real ones are
# generated by install.sh on the target.
JWT_SECRET=build NVR_SECRET_KEY=build BOOTSTRAP_ADMIN_PASSWORD=build \
  docker compose build

echo "==> Pulling external images…"
docker pull "$GO2RTC_IMG"
docker pull "$PG_IMG"   # only used if you enable the 'postgres' profile

echo "==> Saving all images to one tarball (this is the big file)…"
mkdir -p "$OUT"
docker save \
  kanagatly/backend:latest \
  kanagatly/caddy:latest \
  "$GO2RTC_IMG" \
  "$PG_IMG" \
  -o "$OUT/kanagatly-vms-images.tar"

echo "==> Staging runtime files…"
cp docker-compose.yml "$OUT/"
cp "$HERE/install.sh" "$HERE/install.ps1" "$OUT/"
cp "$HERE/README.md" "$OUT/" 2>/dev/null || true
if [ -f backend/.env.example ]; then cp backend/.env.example "$OUT/.env.example"; fi

SIZE="$(du -sh "$OUT" 2>/dev/null | awk '{print $1}')"
cat <<EOF

────────────────────────────────────────────────────────────────────────────
  Offline bundle ready:  $OUT  (${SIZE:-?})
    • kanagatly-vms-images.tar   ← docker load this on the server
    • docker-compose.yml, install.sh, install.ps1, .env.example, README.md

  Copy the whole folder to the target server, then there:
    docker load -i kanagatly-vms-images.tar
    ./install.sh          # Linux
    #  or  .\\install.ps1  # Windows (PowerShell)
────────────────────────────────────────────────────────────────────────────
EOF
