#!/usr/bin/env bash
# Kanagatly VMS — offline installer for Linux / macOS Docker hosts.
#
#   ./install.sh                 first run: generate secrets, detect host IP, up
#   HOST_IP=10.0.0.5 ./install.sh   pin the viewer-facing LAN IP explicitly
#   ./install.sh --hostnet       Linux only: give go2rtc the host network (WebRTC)
#
# Idempotent: re-runs reuse the existing .env (secrets are kept). Images must be
# present already on an air-gapped host — load them first:
#   docker load -i kanagatly-vms-images.tar
set -euo pipefail

# ── locate the compose project (this script may live in deploy/docker or beside
# the compose file in the offline dist/ bundle) ──────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_DIR=""
for d in "$PWD" "$SCRIPT_DIR" "$SCRIPT_DIR/.." "$SCRIPT_DIR/../.."; do
  if [ -f "$d/docker-compose.yml" ]; then COMPOSE_DIR="$(cd "$d" && pwd)"; break; fi
done
[ -n "$COMPOSE_DIR" ] || { echo "✗ docker-compose.yml not found near $SCRIPT_DIR"; exit 1; }
cd "$COMPOSE_DIR"
ENVFILE="$COMPOSE_DIR/.env"

HOSTNET=0
[ "${1:-}" = "--hostnet" ] && HOSTNET=1

c_ok(){ printf "\033[32m✓ %s\033[0m\n" "$*"; }
c_step(){ printf "\033[36m→ %s\033[0m\n" "$*"; }
c_err(){ printf "\033[31m✗ %s\033[0m\n" "$*" >&2; }

command -v docker >/dev/null || { c_err "docker not found on PATH"; exit 1; }
docker compose version >/dev/null 2>&1 || { c_err "'docker compose' v2 required"; exit 1; }

# ── host LAN IP (what viewers/the desktop app connect to) ────────────────────
detect_ip() {
  if [ -n "${HOST_IP:-}" ]; then echo "$HOST_IP"; return; fi
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
  fi
  if [ -z "$ip" ] && command -v ipconfig >/dev/null 2>&1; then  # macOS
    for i in en0 en1 en2; do ip="$(ipconfig getifaddr "$i" 2>/dev/null)"; [ -n "$ip" ] && break; done
  fi
  if [ -z "$ip" ] && command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  echo "$ip"
}

# ── secret helpers (openssl preferred; /dev/urandom fallback) ────────────────
rand_hex(){ if command -v openssl >/dev/null; then openssl rand -hex "$1"; else head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi; }
fernet_key(){  # 32 random bytes, url-safe base64 (Fernet format)
  if command -v openssl >/dev/null; then openssl rand -base64 32 | tr '+/' '-_';
  else head -c 32 /dev/urandom | base64 | tr '+/' '-_'; fi
}

HOST_IP_DETECTED="$(detect_ip)"
[ -n "$HOST_IP_DETECTED" ] || { c_err "could not detect host LAN IP — re-run with HOST_IP=<ip> ./install.sh"; exit 1; }
c_ok "Host LAN IP: $HOST_IP_DETECTED"

# ── .env (generate once; keep secrets on re-run) ─────────────────────────────
if [ ! -f "$ENVFILE" ]; then
  c_step "Generating $ENVFILE (secrets + WebRTC candidates)"
  JWT="$(rand_hex 48)"
  FERNET="$(fernet_key)"
  ADMINPW="$(rand_hex 8)"
  cat > "$ENVFILE" <<EOF
# Generated by install.sh — keep private. Re-running install.sh reuses this file.
JWT_SECRET=$JWT
NVR_SECRET_KEY=$FERNET
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=$ADMINPW
# WebRTC: the host's viewer-facing LAN IP advertised as a go2rtc ICE candidate.
GO2RTC_WEBRTC_CANDIDATES=$HOST_IP_DETECTED:8556
# NVR clock offset (minutes east of UTC). Turkmenistan/UTC+5 = 300.
PLAYBACK_TZ_OFFSET_MINUTES=0
# TLS ingress port the desktop app connects to.
CADDY_HTTPS_PORT=8443
EOF
  c_ok "backend admin password: $ADMINPW  (you'll change it on first login)"
else
  c_ok "Reusing existing $ENVFILE"
  # Refresh the WebRTC candidate if the host IP changed since last run.
  if grep -q '^GO2RTC_WEBRTC_CANDIDATES=' "$ENVFILE"; then
    sed -i.bak "s|^GO2RTC_WEBRTC_CANDIDATES=.*|GO2RTC_WEBRTC_CANDIDATES=$HOST_IP_DETECTED:8556|" "$ENVFILE" && rm -f "$ENVFILE.bak"
  else
    echo "GO2RTC_WEBRTC_CANDIDATES=$HOST_IP_DETECTED:8556" >> "$ENVFILE"
  fi
fi

# ── load pre-built images (air-gapped first run) ─────────────────────────────
if ! docker image inspect kanagatly/backend:latest >/dev/null 2>&1; then
  if [ -f "$COMPOSE_DIR/kanagatly-vms-images.tar" ]; then
    c_step "Loading images from kanagatly-vms-images.tar (first run)…"
    docker load -i "$COMPOSE_DIR/kanagatly-vms-images.tar"
  else
    c_err "Images not loaded and kanagatly-vms-images.tar not found next to docker-compose.yml."
    c_err "Copy the whole bundle folder here (incl. the .tar), then re-run."
    exit 1
  fi
fi

# ── up ───────────────────────────────────────────────────────────────────────
COMPOSE_ARGS=(-f docker-compose.yml)
if [ "$HOSTNET" = 1 ]; then
  [ -f docker-compose.hostnet.yml ] && COMPOSE_ARGS+=(-f docker-compose.hostnet.yml) || c_err "hostnet overlay missing — continuing bridged"
  c_step "Starting stack (Linux host-network go2rtc)…"
else
  c_step "Starting stack…"
fi
docker compose "${COMPOSE_ARGS[@]}" up -d

# ── wait for readiness (through Caddy TLS, self-signed → -k) ──────────────────
PORT="$(sed -n 's/^CADDY_HTTPS_PORT=//p' "$ENVFILE" | tr -d '[:space:]')"; PORT="${PORT:-8443}"
c_step "Waiting for the backend to become ready…"
READY=0
for i in $(seq 1 60); do
  if curl -fsSk "https://127.0.0.1:$PORT/readyz" >/dev/null 2>&1; then READY=1; break; fi
  sleep 2
done

echo
if [ "$READY" = 1 ]; then
  c_ok "Kanagatly VMS is running"
  echo "  → Open the desktop app and connect to:  https://$HOST_IP_DETECTED:$PORT"
  echo "  → Sign in as 'admin' (password shown above / in $ENVFILE); you'll be asked to change it."
else
  c_err "Backend did not report ready in time. Check logs:  docker compose logs -f backend"
  exit 1
fi
