# Kanagatly VMS - offline installer for Windows (Docker Desktop).
#
#   powershell -ExecutionPolicy Bypass -File install.ps1
#   powershell -ExecutionPolicy Bypass -File install.ps1 -HostIp 10.0.0.5
#
# Idempotent: re-runs reuse .env (secrets kept). On an air-gapped host, load the
# images first:  docker load -i kanagatly-vms-images.tar
[CmdletBinding()]
param(
  [string]$HostIp = ""
)
$ErrorActionPreference = "Stop"

function Ok($m){ Write-Host "[ok] $m" -ForegroundColor Green }
function Step($m){ Write-Host "-> $m" -ForegroundColor Cyan }
function Err($m){ Write-Host "[x] $m" -ForegroundColor Red }

# ── locate compose project ───────────────────────────────────────────────────
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$composeDir = $null
foreach ($d in @((Get-Location).Path, $scriptDir, (Join-Path $scriptDir ".."), (Join-Path $scriptDir "..\.."))) {
  if (Test-Path (Join-Path $d "docker-compose.yml")) { $composeDir = (Resolve-Path $d).Path; break }
}
if (-not $composeDir) { Err "docker-compose.yml not found near $scriptDir"; exit 1 }
Set-Location $composeDir
$envFile = Join-Path $composeDir ".env"

# ── prereqs ──────────────────────────────────────────────────────────────────
try { docker version | Out-Null } catch { Err "Docker not found / not running"; exit 1 }
try { docker compose version | Out-Null } catch { Err "'docker compose' v2 required"; exit 1 }

# ── host LAN IP ──────────────────────────────────────────────────────────────
function Detect-Ip {
  if ($HostIp) { return $HostIp }
  $ip = Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway -ne $null -and $_.NetAdapter.Status -eq "Up" } |
        Select-Object -First 1 -ExpandProperty IPv4Address | Select-Object -First 1 -ExpandProperty IPAddress
  if (-not $ip) {
    $ip = (Get-NetIPAddress -AddressFamily IPv4 |
      Where-Object { $_.IPAddress -match '^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)' -and $_.IPAddress -notmatch '^169\.254' } |
      Select-Object -First 1 -ExpandProperty IPAddress)
  }
  return $ip
}
$hostIpVal = Detect-Ip
if (-not $hostIpVal) { Err "Could not detect host LAN IP - re-run with -HostIp <ip>"; exit 1 }
Ok "Host LAN IP: $hostIpVal"

# ── secret helpers ───────────────────────────────────────────────────────────
function Rand-Hex([int]$bytes){ -join ((1..$bytes) | ForEach-Object { '{0:x2}' -f (Get-Random -Max 256) }) }
function Fernet-Key {
  $b = New-Object 'System.Byte[]' 32
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
  ([Convert]::ToBase64String($b)) -replace '\+','-' -replace '/','_'
}

# ── .env ─────────────────────────────────────────────────────────────────────
if (-not (Test-Path $envFile)) {
  Step "Generating .env (secrets + WebRTC candidates)"
  $jwt = Rand-Hex 48
  $fernet = Fernet-Key
  $adminpw = Rand-Hex 8
  @"
# Generated by install.ps1 - keep private. Re-running reuses this file.
JWT_SECRET=$jwt
NVR_SECRET_KEY=$fernet
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=$adminpw
# WebRTC: host viewer-facing LAN IP advertised as a go2rtc ICE candidate.
GO2RTC_WEBRTC_CANDIDATES=$($hostIpVal):8556
# NVR clock offset (minutes east of UTC). Turkmenistan/UTC+5 = 300.
PLAYBACK_TZ_OFFSET_MINUTES=0
# TLS ingress port the desktop app connects to.
CADDY_HTTPS_PORT=8443
"@ | Set-Content -Encoding ascii $envFile
  Ok "backend admin password: $adminpw  (you'll change it on first login)"
} else {
  Ok "Reusing existing .env"
  $lines = Get-Content $envFile
  if ($lines -match '^GO2RTC_WEBRTC_CANDIDATES=') {
    $lines = $lines -replace '^GO2RTC_WEBRTC_CANDIDATES=.*', "GO2RTC_WEBRTC_CANDIDATES=$($hostIpVal):8556"
  } else {
    $lines += "GO2RTC_WEBRTC_CANDIDATES=$($hostIpVal):8556"
  }
  $lines | Set-Content -Encoding ascii $envFile
}

# NOTE: Docker Desktop for Windows has no host networking, so go2rtc runs
# bridged with published :8556 + the candidate above. WebRTC may still fall back
# to MSE on some networks - MSE always works via the :8443 proxy.

Step "Starting stack..."
docker compose -f docker-compose.yml up -d

# ── wait for readiness ───────────────────────────────────────────────────────
$port = 8443
$m = Select-String -Path $envFile -Pattern '^CADDY_HTTPS_PORT=(\d+)'
if ($m) { $port = [int]$m.Matches[0].Groups[1].Value }
Step "Waiting for the backend to become ready..."
# Self-signed cert: PS 7+ uses -SkipCertificateCheck; Windows PowerShell 5.1
# needs a global validation callback instead.
$ps7 = $PSVersionTable.PSVersion.Major -ge 6
if (-not $ps7) { [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true } }
$ready = $false
for ($i=0; $i -lt 60; $i++) {
  try {
    if ($ps7) {
      Invoke-WebRequest -Uri "https://127.0.0.1:$port/readyz" -SkipCertificateCheck -TimeoutSec 4 -UseBasicParsing | Out-Null
    } else {
      Invoke-WebRequest -Uri "https://127.0.0.1:$port/readyz" -TimeoutSec 4 -UseBasicParsing | Out-Null
    }
    $ready = $true; break
  } catch { Start-Sleep -Seconds 2 }
}

Write-Host ""
if ($ready) {
  Ok "Kanagatly VMS is running"
  Write-Host "  -> Open the desktop app and connect to:  https://$($hostIpVal):$port"
  Write-Host "  -> Sign in as 'admin' (password in .env); you'll be asked to change it."
} else {
  Err "Backend did not report ready in time. Check logs:  docker compose logs -f backend"
  exit 1
}
