# Kanagatly VMS SERVER — post-install configuration, run ELEVATED by the Inno
# Setup installer's [Run] step (double-click .exe → wizard → this).
#
# Everything here is driven by the BUNDLED embeddable python (python\python.exe)
# staged next to this script — NEVER a system Python. It:
#   * detects the box's LAN IP,
#   * generates backend\.env secrets on first run (kept verbatim on reinstall),
#   * renders the runtime go2rtc.yaml (WebRTC ICE candidate for THIS box),
#   * runs `alembic upgrade head` + `app.create_admin`,
#   * bakes WWW_ROOT + HTTPS port into the Caddyfile,
#   * registers + starts the three NSSM services, waits for /readyz, prints URL.
#
# Idempotent: reruns reuse an existing backend\.env (secrets preserved) and just
# refresh the WebRTC candidate + binaries/services for the current host IP.
[CmdletBinding()]
param(
  [string]$InstallDir = "",
  [string]$HostIp = "",
  [int]$HttpsPort = 8443
)
$ErrorActionPreference = "Stop"

function Ok($m){ Write-Host "[ok] $m" -ForegroundColor Green }
function Step($m){ Write-Host "-> $m" -ForegroundColor Cyan }
function Err($m){ Write-Host "[x] $m" -ForegroundColor Red }

# The installer runs this from {app}; default to the script's own directory so a
# manual re-run also works.
if (-not $InstallDir) { $InstallDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
$src = $InstallDir

# Capture EVERYTHING this console prints to a file so a failed/flashed install is
# diagnosable after the window closes. (The cmd window is transient; this isn't.)
try { Start-Transcript -Path (Join-Path $InstallDir "install-log.txt") -Force | Out-Null } catch {}

# ── admin check (needed to register services) ────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal] `
  [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
  [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { Err "postinstall.ps1 must run ELEVATED (the installer does this automatically)."; exit 1 }

# ── locate the BUNDLED python + nssm (no system dependencies) ────────────────
$py   = Join-Path $InstallDir "python\python.exe"
$nssm = Join-Path $InstallDir "bin\nssm.exe"
foreach ($f in @($py, $nssm, "bin\go2rtc.exe","bin\ffmpeg.exe","bin\caddy.exe",
                 "backend\app","backend\alembic","backend\alembic.ini",
                 "www\index.html","Caddyfile","go2rtc.base.yaml")) {
  $p = if ([System.IO.Path]::IsPathRooted($f)) { $f } else { Join-Path $InstallDir $f }
  if (-not (Test-Path $p)) { Err "install is incomplete: missing $f"; exit 1 }
}
Ok "Bundled python: $py"
Ok "Bundled NSSM  : $nssm"

# ── runtime dirs (go2rtc + caddy state) ──────────────────────────────────────
foreach ($d in @(".go2rtc",".caddy\data",".caddy\config")) {
  New-Item -ItemType Directory -Force -Path (Join-Path $InstallDir $d) | Out-Null
}

$envFile   = Join-Path $InstallDir "backend\.env"
$ffmpegBin = Join-Path $InstallDir "bin\ffmpeg.exe"

# ── host LAN IP ──────────────────────────────────────────────────────────────
function Detect-Ip {
  if ($HostIp) { return $HostIp }
  $ip = Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway -ne $null -and $_.NetAdapter.Status -eq "Up" } |
        Select-Object -First 1 -ExpandProperty IPv4Address | Select-Object -First 1 -ExpandProperty IPAddress
  if (-not $ip) {
    $ip = (Get-NetIPAddress -AddressFamily IPv4 |
      Where-Object { $_.IPAddress -match '^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)' -and $_.IPAddress -notmatch '^169\.254' } |
      Select-Object -First 1 -ExpandProperty IPAddress)
  }
  return $ip
}
$hostIpVal = Detect-Ip
if (-not $hostIpVal) { Err "Could not detect host LAN IP - re-run with -HostIp <ip>"; exit 1 }
Ok "Host LAN IP: $hostIpVal"

# ── secrets + .env (generate once; keep secrets + tunables on re-run) ────────
function Rand-Hex([int]$bytes){ -join ((1..$bytes) | ForEach-Object { '{0:x2}' -f (Get-Random -Max 256) }) }
if (-not (Test-Path $envFile)) {
  Step "Generating $envFile (secrets + WebRTC candidates)"
  $jwt = Rand-Hex 48
  $fernet = (& $py -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())").Trim()
  $adminpw = Rand-Hex 8
  @"
# Generated by the Kanagatly VMS Server installer - keep private. Reinstall reuses this file.
DATABASE_URL=sqlite+aiosqlite:///./dss.db
JWT_SECRET=$jwt
NVR_SECRET_KEY=$fernet
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=$adminpw
RELAY=go2rtc
# Bundled static ffmpeg (playback + re-encode).
REENCODE_FFMPEG_BIN=$ffmpegBin
# WebRTC: this box's viewer-facing LAN IP advertised as a go2rtc ICE candidate.
GO2RTC_WEBRTC_CANDIDATES=$($hostIpVal):8556
# NVR clock offset (minutes east of UTC). Turkmenistan/UTC+5 = 300.
PLAYBACK_TZ_OFFSET_MINUTES=0
"@ | Set-Content -Encoding ascii $envFile
  Ok "backend admin password: $adminpw  (you'll change it on first login)"
} else {
  Ok "Reusing existing $envFile"
  $lines = Get-Content $envFile
  if ($lines -match '^GO2RTC_WEBRTC_CANDIDATES=') { $lines = $lines -replace '^GO2RTC_WEBRTC_CANDIDATES=.*', "GO2RTC_WEBRTC_CANDIDATES=$($hostIpVal):8556" }
  else { $lines += "GO2RTC_WEBRTC_CANDIDATES=$($hostIpVal):8556" }
  if ($lines -match '^REENCODE_FFMPEG_BIN=') { $lines = $lines -replace '^REENCODE_FFMPEG_BIN=.*', "REENCODE_FFMPEG_BIN=$ffmpegBin" }
  else { $lines += "REENCODE_FFMPEG_BIN=$ffmpegBin" }
  $lines | Set-Content -Encoding ascii $envFile
}

# ── bake the SPA root + HTTPS port into the Caddyfile (forward-slash, quoted)
# so Caddy needs NO service env for the least-reliable link — same fix as the
# native install.ps1. ──────────────────────────────────────────────────────────
$wwwFwd = '"' + (((Join-Path $InstallDir "www")) -replace '\\','/') + '"'
$caddyfilePath = Join-Path $InstallDir "Caddyfile"
$cf = Get-Content $caddyfilePath -Raw
$cf = $cf -replace '\{\$WWW_ROOT\}', $wwwFwd
$cf = $cf -replace ':\{\$CADDY_HTTPS_PORT:8443\}', ":$HttpsPort"
Set-Content -Encoding ascii $caddyfilePath $cf
Ok "Caddyfile rendered (root=$wwwFwd port=$HttpsPort)"

# ── render go2rtc runtime config (WebRTC candidates for THIS box) ────────────
Step "Rendering go2rtc config"
Push-Location (Join-Path $InstallDir "backend")
try {
  & $py -m app.services.go2rtc_config --base (Join-Path $InstallDir "go2rtc.base.yaml") --out (Join-Path $InstallDir ".go2rtc\go2rtc.yaml")
  if ($LASTEXITCODE -ne 0) { throw "render failed" }
} catch {
  Err "go2rtc config render failed - copying template as-is"
  Copy-Item -Force (Join-Path $InstallDir "go2rtc.base.yaml") (Join-Path $InstallDir ".go2rtc\go2rtc.yaml")
} finally { Pop-Location }

# ── DB migrations + admin (all via the bundled python -m …, so relocatable) ──
Step "Applying database migrations (alembic upgrade head)"
Push-Location (Join-Path $InstallDir "backend")
try {
  & $py -m alembic upgrade head
  if ($LASTEXITCODE -ne 0) { throw "alembic failed" }
  Step "Ensuring the admin account exists"
  & $py -m app.create_admin
} finally { Pop-Location }

# ── NSSM services ─────────────────────────────────────────────────────────────
function Reinstall-Service($name, $exe, $argline, $appdir, $envPairs) {
  & $nssm status $name *> $null
  if ($LASTEXITCODE -eq 0) { & $nssm stop $name *> $null; & $nssm remove $name confirm *> $null }
  & $nssm install $name $exe $argline
  & $nssm set $name AppDirectory $appdir
  & $nssm set $name Start SERVICE_AUTO_START
  & $nssm set $name AppStdout (Join-Path $InstallDir "$name.log")
  & $nssm set $name AppStderr (Join-Path $InstallDir "$name.log")
  if ($envPairs) { & $nssm set $name AppEnvironmentExtra $envPairs }
}

Step "Registering NSSM services"
Reinstall-Service "dahua-go2rtc" (Join-Path $InstallDir "bin\go2rtc.exe") `
  ("-config `"" + (Join-Path $InstallDir ".go2rtc\go2rtc.yaml") + "`"") $InstallDir $null

Reinstall-Service "dahua-backend" $py `
  "-m uvicorn app.main:app --host 0.0.0.0 --port 8000" (Join-Path $InstallDir "backend") $null

$caddyEnv = @(
  "WWW_ROOT=$(Join-Path $InstallDir 'www')",
  "CADDY_HTTPS_PORT=$HttpsPort",
  "BACKEND_UPSTREAM=127.0.0.1:8000",
  "GO2RTC_UPSTREAM=127.0.0.1:1984",
  "XDG_DATA_HOME=$(Join-Path $InstallDir '.caddy\data')",
  "XDG_CONFIG_HOME=$(Join-Path $InstallDir '.caddy\config')"
)
Reinstall-Service "dahua-caddy" (Join-Path $InstallDir "bin\caddy.exe") `
  ("run --config `"" + (Join-Path $InstallDir "Caddyfile") + "`" --adapter caddyfile") $InstallDir $caddyEnv

Step "Starting services"
& $nssm start dahua-go2rtc  | Out-Null
& $nssm start dahua-backend | Out-Null
& $nssm start dahua-caddy   | Out-Null
Ok "services registered + started"

# ── wait for readiness (through Caddy TLS, self-signed) ──────────────────────
Step "Waiting for the backend to become ready..."
$ps7 = $PSVersionTable.PSVersion.Major -ge 6
if (-not $ps7) { [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true } }
$ready = $false
for ($i=0; $i -lt 60; $i++) {
  try {
    if ($ps7) { Invoke-WebRequest -Uri "https://127.0.0.1:$HttpsPort/readyz" -SkipCertificateCheck -TimeoutSec 4 -UseBasicParsing | Out-Null }
    else      { Invoke-WebRequest -Uri "https://127.0.0.1:$HttpsPort/readyz" -TimeoutSec 4 -UseBasicParsing | Out-Null }
    $ready = $true; break
  } catch { Start-Sleep -Seconds 2 }
}

try { Stop-Transcript | Out-Null } catch {}

Write-Host ""
if ($ready) {
  Ok "Kanagatly VMS Server is running"
  Write-Host "  -> Open the desktop app and connect to:  https://$($hostIpVal):$HttpsPort"
  Write-Host "  -> Sign in as 'admin' (password shown above / in $envFile); you'll be asked to change it."
  Write-Host "  -> Services: Get-Service dahua-go2rtc,dahua-backend,dahua-caddy   Logs: $InstallDir\dahua-*.log"
} else {
  Err "Backend did not report ready in time. Check the logs in $InstallDir\dahua-*.log"
  exit 1
}
