/**
 * DOM element references — cached at module load.
 */

const $ = (id) => document.getElementById(id);

export const dom = {
  sidebarToggle:  $("sidebar-toggle"),
  sidebar:        $("sidebar"),
  gridSizeSel:    $("grid-size"),
  layoutSel:      $("layout-select"),
  saveLayoutBtn:  $("save-layout-btn"),
  patrolBtn:      $("patrol-btn"),
  patrolInterval: $("patrol-interval"),
  patrolCountdown:$("patrol-countdown"),
  search:         $("search"),
  statusToggle:   $("status-toggle"),
  statusSummary:  $("status-summary"),
  shortcutsBtn:   $("shortcuts-btn"),
  showAllBtn:     $("show-all-btn"),
  addGroupBtn:    $("add-group-btn"),
  nvrTree:        $("nvr-tree"),
  groupTree:      $("group-tree"),
  gridContainer:  $("grid-container"),
  cameraGrid:     $("camera-grid"),
  sbOnline:       $("sb-online"),
  sbConnecting:   $("sb-connecting"),
  sbError:        $("sb-error"),
  sbTotal:        $("sb-total"),
  sbPage:         $("sb-page"),
  sbFilter:       $("sb-filter"),
  fsOverlay:      $("fullscreen-overlay"),
  fsTitle:        $("fs-title"),
  fsVideo:        $("fs-video"),
  fsBuffer:       $("fs-buffer"),
  fsQualityBtn:   $("fs-quality-btn"),
  fsSnapshotBtn:  $("fs-snapshot-btn"),
  fsCloseBtn:     $("fs-close-btn"),
  statusPanel:    $("status-panel"),
  statusList:     $("status-list"),
  reconnectAllBtn:$("reconnect-all-btn"),
  shortcutsModal: $("shortcuts-modal"),
  groupDialog:    $("group-dialog"),
  groupNameInput: $("group-name-input"),
  groupCreateBtn: $("group-create-btn"),
  groupCancelBtn: $("group-cancel-btn"),
  groupCamSearch: $("group-cam-search"),
  groupCamList:   $("group-cam-list"),
  groupSelectAll: $("group-select-all"),
  groupSelectedCount: $("group-selected-count"),
  groupDialogTitle: $("group-dialog-title"),
  layoutDialog:   $("layout-dialog"),
  layoutNameInput:$("layout-name-input"),
  layoutSaveBtn:  $("layout-save-btn"),
  layoutCancelBtn:$("layout-cancel-btn"),
  contextMenu:    $("context-menu"),
  contextItems:   $("context-menu-items"),
  settingsBtn:    $("settings-btn"),
  settingsModal:  $("settings-modal"),
  settingsPort:   $("settings-port"),
  settingsUser:   $("settings-user"),
  settingsPass:   $("settings-pass"),
  settingsSubtype:$("settings-subtype"),
  settingsNvrCount:$("settings-nvr-count"),
  settingsNvrBody:$("settings-nvr-body"),
  settingsNewId:  $("settings-new-id"),
  settingsNewLabel:$("settings-new-label"),
  settingsNewIp:  $("settings-new-ip"),
  settingsNewCh:  $("settings-new-ch"),
  settingsNewPass:$("settings-new-pass"),
  settingsNewVendor:$("settings-new-vendor"),
  settingsAddBtn: $("settings-add-btn"),
  settingsSaveBtn:$("settings-save-btn"),
  settingsRestartBtn:$("settings-restart-btn"),
  settingsStatus: $("settings-status"),
  settingsStreamSource: $("settings-stream-source"),
  settingsServerUrl: $("settings-server-url"),
  settingsMaxRetries: $("settings-max-retries"),
  settingsRetryDelay: $("settings-retry-delay"),
  settingsMaxConcurrent: $("settings-max-concurrent"),
  settingsHealthBtn: $("settings-health-btn"),
  settingsHealthStatus: $("settings-health-status"),
  settingsTestAllBtn: $("settings-test-all-btn"),
  settingsClearBansBtn: $("settings-clear-bans-btn"),
  settingsImportBtn: $("settings-import-btn"),
  settingsEventsBtn: $("settings-events-btn"),
  settingsCurPw:  $("settings-cur-pw"),
  settingsNewPw:  $("settings-new-pw"),
  settingsChpwBtn:$("settings-chpw-btn"),
  settingsChpwStatus:$("settings-chpw-status"),
  importDialog:   $("import-dialog"),
  importTextarea: $("import-textarea"),
  importStatus:   $("import-status"),
  importApplyBtn: $("import-apply-btn"),
  importCancelBtn:$("import-cancel-btn"),
  eventsDialog:   $("events-dialog"),
  eventsList:     $("events-list"),
  toastContainer: $("toast-container"),
  logoutBtn:      $("logout-btn"),
  warningBanner:  $("warning-banner"),
};
