/**
 * DOM element references — cached at module load.
 */

const $ = (id) => document.getElementById(id);

export const dom = {
  sidebarToggle:  $("sidebar-toggle"),
  sidebar:        $("sidebar"),
  gridSizeSel:    $("grid-size"),
  layoutSel:      $("layout-select"),
  saveLayoutBtn:  $("save-layout-btn"),
  patrolBtn:      $("patrol-btn"),
  patrolInterval: $("patrol-interval"),
  patrolCountdown:$("patrol-countdown"),
  search:         $("search"),
  statusToggle:   $("status-toggle"),
  statusSummary:  $("status-summary"),
  shortcutsBtn:   $("shortcuts-btn"),
  showAllBtn:     $("show-all-btn"),
  addGroupBtn:    $("add-group-btn"),
  nvrTree:        $("nvr-tree"),
  groupTree:      $("group-tree"),
  gridContainer:  $("grid-container"),
  cameraGrid:     $("camera-grid"),
  sbOnline:       $("sb-online"),
  sbConnecting:   $("sb-connecting"),
  sbError:        $("sb-error"),
  sbTotal:        $("sb-total"),
  sbPage:         $("sb-page"),
  sbFilter:       $("sb-filter"),
  fsOverlay:      $("fullscreen-overlay"),
  fsTitle:        $("fs-title"),
  fsVideo:        $("fs-video"),
  fsBuffer:       $("fs-buffer"),
  fsQualityBtn:   $("fs-quality-btn"),
  fsSnapshotBtn:  $("fs-snapshot-btn"),
  fsCloseBtn:     $("fs-close-btn"),
  statusPanel:    $("status-panel"),
  statusList:     $("status-list"),
  reconnectAllBtn:$("reconnect-all-btn"),
  shortcutsModal: $("shortcuts-modal"),
  groupDialog:    $("group-dialog"),
  groupNameInput: $("group-name-input"),
  groupCreateBtn: $("group-create-btn"),
  groupCancelBtn: $("group-cancel-btn"),
  groupCamSearch: $("group-cam-search"),
  groupCamList:   $("group-cam-list"),
  groupSelectAll: $("group-select-all"),
  groupSelectedCount: $("group-selected-count"),
  groupDialogTitle: $("group-dialog-title"),
  layoutDialog:   $("layout-dialog"),
  layoutNameInput:$("layout-name-input"),
  layoutSaveBtn:  $("layout-save-btn"),
  layoutCancelBtn:$("layout-cancel-btn"),
  contextMenu:    $("context-menu"),
  contextItems:   $("context-menu-items"),
  settingsBtn:        $("settings-btn"),
  settingsModal:      $("settings-modal"),
  settingsNvrCount:   $("settings-nvr-count"),
  settingsNvrBody:    $("settings-nvr-body"),
  settingsNewId:      $("settings-new-id"),
  settingsNewLabel:   $("settings-new-label"),
  settingsNewIp:      $("settings-new-ip"),
  settingsNewPort:    $("settings-new-port"),
  settingsNewUser:    $("settings-new-user"),
  settingsNewPass:    $("settings-new-pass"),
  settingsNewVendor:  $("settings-new-vendor"),
  settingsNewCh:      $("settings-new-ch"),
  settingsNewRegion:  $("settings-new-region"),
  settingsNewEnabled: $("settings-new-enabled"),
  settingsAddBtn:     $("settings-add-btn"),
  settingsAddStatus:  $("settings-add-status"),
  settingsAdvToggle:  $("settings-adv-toggle"),
  settingsAdvPanel:   $("settings-adv-panel"),
  settingsStatus:     $("settings-status"),
  settingsHealthBtn:  $("settings-health-btn"),
  settingsReconcileBtn:$("settings-reconcile-btn"),
  settingsEventsBtn:  $("settings-events-btn"),
  settingsRefreshBtn: $("settings-refresh-btn"),
  settingsCurPw:      $("settings-cur-pw"),
  settingsNewPw:      $("settings-new-pw"),
  settingsChpwBtn:    $("settings-chpw-btn"),
  settingsChpwStatus: $("settings-chpw-status"),
  camerasDialog:      $("cameras-dialog"),
  camerasDialogNvr:   $("cameras-dialog-nvr"),
  camerasBody:        $("cameras-body"),
  camerasStatus:      $("cameras-status"),
  camerasNewCh:       $("cameras-new-ch"),
  camerasNewName:     $("cameras-new-name"),
  camerasNewSub:      $("cameras-new-sub"),
  camerasNewMain:     $("cameras-new-main"),
  camerasNewEnabled:  $("cameras-new-enabled"),
  camerasAddBtn:      $("cameras-add-btn"),
  camerasAddStatus:   $("cameras-add-status"),
  eventsDialog:       $("events-dialog"),
  eventsList:         $("events-list"),
  toastContainer: $("toast-container"),
  logoutBtn:      $("logout-btn"),
  warningBanner:  $("warning-banner"),
};
