#!/usr/bin/env bash
#
# Kanagatly VMS — NATIVE (no-Docker) offline installer for LINUX (systemd).
#
#   sudo ./install.sh                       install to /opt/kanagatly-vms
#   sudo INSTALL_DIR=/srv/vms ./install.sh  pick the install dir
#   sudo HOST_IP=10.0.0.5 ./install.sh      pin the viewer-facing LAN IP
#
# Run from inside the bundle folder produced by build-bundle.sh. Fully offline:
# installs Python deps from wheelhouse/, drops the bundled go2rtc/ffmpeg/caddy
# binaries, generates secrets, runs migrations, and registers + starts three
# systemd units (kanagatly-go2rtc, kanagatly-backend, kanagatly-caddy).
#
# Idempotent: re-runs reuse an existing backend/.env (secrets kept) and just
# refresh binaries/code + the WebRTC candidate for the current host IP.
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"        # the bundle folder
INSTALL_DIR="${INSTALL_DIR:-/opt/kanagatly-vms}"
HTTPS_PORT="${HTTPS_PORT:-8443}"

c_ok(){ printf "\033[32m✓ %s\033[0m\n" "$*"; }
c_step(){ printf "\033[36m→ %s\033[0m\n" "$*"; }
c_err(){ printf "\033[31m✗ %s\033[0m\n" "$*" >&2; }

[ "$(id -u)" = "0" ] || { c_err "run as root (sudo ./install.sh) — needs systemd + $INSTALL_DIR"; exit 1; }
command -v systemctl >/dev/null || { c_err "systemd (systemctl) not found — this installer targets systemd Linux"; exit 1; }

# ── locate a Python 3.12+ interpreter (target must provide one; see README) ──
find_python() {
  for p in python3.12 python3.13 python3; do
    if command -v "$p" >/dev/null 2>&1; then
      if "$p" -c 'import sys; sys.exit(0 if sys.version_info[:2] >= (3,12) else 1)' 2>/dev/null; then
        command -v "$p"; return 0
      fi
    fi
  done
  return 1
}
PY="$(find_python)" || { c_err "Python 3.12+ not found. Install it (e.g. 'apt install python3.12 python3.12-venv') or bundle one — see README."; exit 1; }
c_ok "Python: $PY ($($PY -V 2>&1))"

for f in wheelhouse bin/go2rtc bin/ffmpeg bin/caddy backend/requirements.txt www/index.html Caddyfile go2rtc.base.yaml; do
  [ -e "$SRC/$f" ] || { c_err "bundle is incomplete: missing $f (re-run build-bundle.sh)"; exit 1; }
done

# ── stage files into INSTALL_DIR (preserve an existing .env) ─────────────────
c_step "Installing into $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"/{bin,backend,www,.go2rtc,.caddy}
cp -a "$SRC/bin/." "$INSTALL_DIR/bin/"
cp -a "$SRC/www/." "$INSTALL_DIR/www/"
cp -a "$SRC/Caddyfile" "$SRC/go2rtc.base.yaml" "$INSTALL_DIR/"
# backend source — refresh code but never clobber a live .env
rsync -a --delete --exclude='.env' --exclude='.venv' --exclude='*.db*' \
  "$SRC/backend/" "$INSTALL_DIR/backend/" 2>/dev/null || {
    # rsync may be absent on a minimal host — fall back to cp
    cp -a "$SRC/backend/app" "$SRC/backend/alembic" "$SRC/backend/alembic.ini" \
          "$SRC/backend/requirements.txt" "$INSTALL_DIR/backend/"
  }
chmod +x "$INSTALL_DIR/bin/"* 2>/dev/null || true
c_ok "files staged"

ENVFILE="$INSTALL_DIR/backend/.env"
FFMPEG_BIN="$INSTALL_DIR/bin/ffmpeg"

# ── venv from the offline wheelhouse ─────────────────────────────────────────
VENV="$INSTALL_DIR/venv"
if [ ! -x "$VENV/bin/python" ]; then
  c_step "Creating venv"
  "$PY" -m venv "$VENV"
fi
c_step "Installing backend deps (offline, from wheelhouse)"
"$VENV/bin/python" -m pip install --no-index --find-links "$SRC/wheelhouse" --upgrade pip setuptools wheel >/dev/null 2>&1 || true
"$VENV/bin/python" -m pip install --no-index --find-links "$SRC/wheelhouse" -r "$INSTALL_DIR/backend/requirements.txt"
c_ok "deps installed"

# ── host LAN IP (what viewers / the desktop app connect to) ──────────────────
detect_ip() {
  if [ -n "${HOST_IP:-}" ]; then echo "$HOST_IP"; return; fi
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
  fi
  [ -z "$ip" ] && command -v hostname >/dev/null 2>&1 && ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  echo "$ip"
}
HOST_IP_DETECTED="$(detect_ip)"
[ -n "$HOST_IP_DETECTED" ] || { c_err "could not detect host LAN IP — re-run with HOST_IP=<ip> ./install.sh"; exit 1; }
c_ok "Host LAN IP: $HOST_IP_DETECTED"

# ── secrets + .env (generate once; keep secrets on re-run) ───────────────────
rand_hex(){ if command -v openssl >/dev/null; then openssl rand -hex "$1"; else head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; fi; }
fernet_key(){ "$VENV/bin/python" -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'; }

if [ ! -f "$ENVFILE" ]; then
  c_step "Generating $ENVFILE (secrets + WebRTC candidates)"
  JWT="$(rand_hex 48)"; FERNET="$(fernet_key)"; ADMINPW="$(rand_hex 8)"
  cat > "$ENVFILE" <<EOF
# Generated by deploy/native/install.sh — keep private. Re-running reuses this file.
DATABASE_URL=sqlite+aiosqlite:///./dss.db
JWT_SECRET=$JWT
NVR_SECRET_KEY=$FERNET
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_PASSWORD=$ADMINPW
RELAY=go2rtc
# Bundled static ffmpeg (playback + re-encode).
REENCODE_FFMPEG_BIN=$FFMPEG_BIN
# WebRTC: this box's viewer-facing LAN IP advertised as a go2rtc ICE candidate.
GO2RTC_WEBRTC_CANDIDATES=$HOST_IP_DETECTED:8556
# NVR clock offset (minutes east of UTC). Turkmenistan/UTC+5 = 300.
PLAYBACK_TZ_OFFSET_MINUTES=0
EOF
  chmod 600 "$ENVFILE"
  c_ok "backend admin password: $ADMINPW  (you'll change it on first login)"
else
  c_ok "Reusing existing $ENVFILE"
  # keep the WebRTC candidate + ffmpeg path current for this box/install
  if grep -q '^GO2RTC_WEBRTC_CANDIDATES=' "$ENVFILE"; then
    sed -i "s|^GO2RTC_WEBRTC_CANDIDATES=.*|GO2RTC_WEBRTC_CANDIDATES=$HOST_IP_DETECTED:8556|" "$ENVFILE"
  else echo "GO2RTC_WEBRTC_CANDIDATES=$HOST_IP_DETECTED:8556" >> "$ENVFILE"; fi
  if grep -q '^REENCODE_FFMPEG_BIN=' "$ENVFILE"; then
    sed -i "s|^REENCODE_FFMPEG_BIN=.*|REENCODE_FFMPEG_BIN=$FFMPEG_BIN|" "$ENVFILE"
  else echo "REENCODE_FFMPEG_BIN=$FFMPEG_BIN" >> "$ENVFILE"; fi
fi

# ── render go2rtc runtime config (injects WebRTC candidates for THIS box) ────
c_step "Rendering go2rtc config"
( cd "$INSTALL_DIR/backend" && "$VENV/bin/python" -m app.services.go2rtc_config \
    --base "$INSTALL_DIR/go2rtc.base.yaml" --out "$INSTALL_DIR/.go2rtc/go2rtc.yaml" ) \
  || { c_err "go2rtc config render failed — copying template as-is"; cp "$INSTALL_DIR/go2rtc.base.yaml" "$INSTALL_DIR/.go2rtc/go2rtc.yaml"; }

# ── DB migrations + admin ────────────────────────────────────────────────────
c_step "Applying database migrations (alembic upgrade head)"
( cd "$INSTALL_DIR/backend" && "$VENV/bin/alembic" upgrade head )
c_step "Ensuring the admin account exists"
( cd "$INSTALL_DIR/backend" && "$VENV/bin/python" -m app.create_admin ) || true

# ── systemd units (substitute placeholders → /etc/systemd/system) ────────────
c_step "Registering systemd units"
render_unit() {  # render_unit <src> <dst>
  sed -e "s|@INSTALL_DIR@|$INSTALL_DIR|g" -e "s|@HTTPS_PORT@|$HTTPS_PORT|g" "$1" > "$2"
}
UNITSRC="$SRC/deploy/systemd"
[ -d "$UNITSRC" ] || UNITSRC="$SRC/systemd"
for u in kanagatly-go2rtc kanagatly-backend kanagatly-caddy; do
  render_unit "$UNITSRC/$u.service" "/etc/systemd/system/$u.service"
done
systemctl daemon-reload
systemctl enable --now kanagatly-go2rtc.service kanagatly-backend.service kanagatly-caddy.service
c_ok "services enabled + started"

# ── wait for readiness (through Caddy TLS, self-signed → -k) ─────────────────
c_step "Waiting for the backend to become ready…"
READY=0
for i in $(seq 1 60); do
  if curl -fsSk "https://127.0.0.1:$HTTPS_PORT/readyz" >/dev/null 2>&1; then READY=1; break; fi
  sleep 2
done

echo
if [ "$READY" = 1 ]; then
  c_ok "Kanagatly VMS is running"
  echo "  → Open the desktop app and connect to:  https://$HOST_IP_DETECTED:$HTTPS_PORT"
  echo "  → Sign in as 'admin' (password shown above / in $ENVFILE); you'll be asked to change it."
  echo "  → Services: systemctl status kanagatly-{go2rtc,backend,caddy}"
else
  c_err "Backend did not report ready in time. Check logs:"
  echo "     journalctl -u kanagatly-backend -u kanagatly-go2rtc -u kanagatly-caddy -n 100 --no-pager"
  exit 1
fi
